BMD-5781: update deps
BerlingskeMedia/bpc pull request #123
Opened 2020-12-01 11:31 UTC by bmxpapa

### Jira ticket:
https://berlingskemedia.atlassian.net/browse/BMD-5781

### Pre/Post release actions:
(none)

2020-12-17 07:52 UTC, bmxpiku requested changes

2020-12-17 07:52 UTC, bmxpiku commented on README.md
> +
tbh, for Section Run with docker, I would simply link it to bm.env.sso project and update that one as a separate task

2020-12-17 07:52 UTC, bmxpiku commented on server/index.js
> +        }
as agreed -> only dev env

2020-12-17 09:31 UTC, bmxmaza commented on README.md
> +
If it possible, I'd prefer to create separate `Dockerfile` i.e. `Dodkerfile.dev` and use it in `docker-compose.override.yml` to avoid using `-f` flag. Weuse this in MDB projects.

2020-12-17 09:32 UTC, bmxmaza commented on README.md
> +
Moreover you have two docker-compose files.

2020-12-17 10:07 UTC, bmxpapa commented on README.md
> +
1) about docker-compose
 there is no docker-compose.yml in this project at all, so maybe I can use
docker-compose.yml instead of docker-compose.override.yml

I think docker-compose.yml is usually used only for development

2) about Dockerfile & Dockerfile.dev I would suggest keeping as long as possible the consistency between those files,
so until we don't need  to have two separate docker files lets keep just one

2021-01-11 09:14 UTC, bmxpiku approved these changes

2021-01-11 09:18 UTC, merged